# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '0.0.1'
git_version = 'a2b8c90e5ba1d32f702115b51dfde5f536e5d369'
